"""
Binance Price Aggregator - Daily Average (Airflow 3 Compatible)
================================================================

Aggregates daily Bitcoin price statistics from hourly data
generated by the binance_calculate_hourly DAG.

Reads:
~/airflow/data/binance/hourly/YYYY-MM-DD/hourly_avg.csv

Writes:
~/airflow/data/binance/daily/daily_avg.csv
"""

from datetime import datetime, timedelta
from pathlib import Path
import os

import pandas as pd
from airflow import DAG
from airflow.providers.standard.operators.python import PythonOperator


def calculate_daily_average(**context):
    """
    Calculates daily average price from hourly aggregated data.
    Aggregates the PREVIOUS completed day using Airflow logical time.
    """

    # Airflow logical time
    logical_time = context["logical_date"]

    # We aggregate the previous completed day
    target_date_dt = logical_time - timedelta(days=1)
    target_date = target_date_dt.strftime("%Y-%m-%d")

    airflow_home = Path(
        os.environ.get("AIRFLOW_HOME", "~/airflow")
    ).expanduser()

    hourly_file = (
        airflow_home
        / "data"
        / "binance"
        / "hourly"
        / target_date
        / "hourly_avg.csv"
    )

    if not hourly_file.exists():
        print(f"⚠ No hourly data found at {hourly_file}")
        return

    try:
        df = pd.read_csv(hourly_file)

        if df.empty:
            print(f"⚠ No hourly data available for {target_date}")
            return

        # Ensure sorted by hour
        df = df.sort_values("hour")

        opening_price = df["first_price"].iloc[0]
        closing_price = df["last_price"].iloc[-1]

        price_change = closing_price - opening_price
        price_change_pct = (
            (price_change / opening_price) * 100
            if opening_price > 0
            else 0
        )

        daily_stats = {
            "date": target_date,
            "avg_price": df["avg_price"].mean(),
            "min_price": df["min_price"].min(),
            "max_price": df["max_price"].max(),
            "opening_price": opening_price,
            "closing_price": closing_price,
            "price_change": price_change,
            "price_change_pct": price_change_pct,
            "total_data_points": df["data_points"].sum(),
            "hours_with_data": len(df),
            "calculated_at": logical_time.strftime("%Y-%m-%d %H:%M:%S"),
        }

        daily_df = pd.DataFrame([daily_stats])

        # Output location
        output_dir = airflow_home / "data" / "binance" / "daily"
        output_dir.mkdir(parents=True, exist_ok=True)

        output_file = output_dir / "daily_avg.csv"

        # Append without duplicates
        if output_file.exists():
            existing_df = pd.read_csv(output_file)
            existing_df = existing_df[existing_df["date"] != target_date]
            daily_df = pd.concat([existing_df, daily_df], ignore_index=True)

        daily_df = daily_df.sort_values("date")
        daily_df.to_csv(output_file, index=False)

        print("✅ Daily aggregation completed")
        print(f"Date: {target_date}")
        print(f"Average Price: ${daily_stats['avg_price']:.2f}")
        print(f"Price Change: ${price_change:.2f} ({price_change_pct:.2f}%)")
        print(f"Hours with Data: {daily_stats['hours_with_data']}")
        print(f"Saved to: {output_file}")

        return daily_stats

    except Exception as e:
        print(f"❌ Error calculating daily average: {e}")
        raise


# DAG Definition (Airflow 3)
dag = DAG(
    dag_id="binance_calculate_daily",
    description="Calculates daily average Bitcoin price from hourly data",
    schedule=timedelta(days=1),
    start_date=datetime(2024, 1, 1),
    catchup=False,
    tags=["binance", "crypto", "daily", "aggregation"],
    default_args={
        "retries": 2,
        "retry_delay": timedelta(minutes=10),
    },
)


calculate_daily = PythonOperator(
    task_id="calculate_daily_average",
    python_callable=calculate_daily_average,
    dag=dag,
)

